name: 'Tear Down Script via Terraform'

on:
  repository_dispatch:
    types: [destroy]
  workflow_dispatch:
    
jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: crunchy-backups
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9
          terraform_wrapper: false
      - name: Terraform Init
        id: init
        if: contains(fromJSON('["aspiredu-au"]'), github.event.client_payload.backend)
        run: terraform init -backend-config="key=${{ github.event.client_payload.backend }}/terraform.tfstate"
          working-directory: ./au
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
      - name: Terraform Destroy
        id: destroy
        if: contains(fromJSON('["aspiredu-au"]'), github.event.client_payload.backend)
        run: terraform destroy -auto-approve -input=false
          working-directory: ./au
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
      - name: Terraform Init
        id: init
        if: contains(fromJSON('["aspiredu-au"]'), github.event.client_payload.backend) == false
        run: terraform init -backend-config="key=${{ github.event.client_payload.backend }}/terraform.tfstate"
          working-directory: ./us-east
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
      - name: Terraform Destroy
        id: destroy
        if: contains(fromJSON('["aspiredu-au"]'), github.event.client_payload.backend) == false
        run: terraform destroy -auto-approve -input=false
          working-directory: ./us-east
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
