name: 'Start Script via Terraform'

on:
  workflow_dispatch:
  # schedule:
    # - cron: '0 3 * * *'

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: crunchy-backups
    defaults:
      run:
        working-directory: ./us-east
    strategy:
      matrix:
        backend: [aspiredu-prd-a, aspiredu-prd-b, aspiredu-prd-c, aspiredu-prd-d, aspiredu-prd-e, aspiredu-prd-g, aspiredu-prd-h, aspiredu-prd-i, aspiredu-prd-j, aspiredu-prd-k, aspiredu-prd-l, aspireprod, aspiredu-ms]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.9
          terraform_wrapper: false
      - name: Terraform Init
        id: init
        run: terraform init -backend-config="key=${{ matrix.backend }}/terraform.tfstate"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -input=false -no-color -out tf.plan
        env:
          TF_VAR_CRUNCHY_TEAM_ID: ${{ vars.CRUNCHY_TEAM_ID }}
          TF_VAR_CRUNCHY_API_KEY: ${{ secrets.CRUNCHY_API_KEY }}
          TF_VAR_ASPIRE_AWS_ACCESS_KEY_ID: ${{ secrets.ASPIRE_AWS_ACCESS_KEY_ID }}
          TF_VAR_ASPIRE_AWS_SECRET_ACCESS_KEY: ${{ secrets.ASPIRE_AWS_SECRET_ACCESS_KEY }}
          TF_VAR_GIT_PAT: ${{ secrets.GIT_PAT }}
          TF_VAR_ASPIRE_BACKEND: ${{ matrix.backend }}
          AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
      - name: Terraform Apply
        id: apply
        run: |
          terraform apply -auto-approve -input=false tf.plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
