name: 'Start Script via Terraform for AU'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *' # Everyday at 07:00 UTC (03:00 Eastern)

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: crunchy-backups
    defaults:
      run:
        working-directory: ./au
    strategy:
      matrix:
        backend: [aspiredu-au]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Deploy With Terraform
        id: deployAttempt1
        uses: ./.github/actions/tf-deploy-composite
        continue-on-error: true
        with:
          TERRAFORM_AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
          TERRAFORM_AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
          CRUNCHY_TEAM_ID: ${{ vars.CRUNCHY_TEAM_ID }}
          CRUNCHY_API_KEY: ${{ secrets.CRUNCHY_API_KEY }}
          ASPIRE_AWS_ACCESS_KEY_ID: ${{ secrets.ASPIRE_AWS_ACCESS_KEY_ID }}
          ASPIRE_AWS_SECRET_ACCESS_KEY: ${{ secrets.ASPIRE_AWS_SECRET_ACCESS_KEY }}
          GIT_PAT: ${{ secrets.GIT_PAT }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          backend: ${{ matrix.backend }}
          WORKING_DIR: ./au
      - name: Deploy With Terraform Attempt 2
        id: deployAttempt2
        uses: ./.github/actions/tf-deploy-composite
        if: steps.deployAttempt1.outcome == 'failure'
        continue-on-error: true
        with:
          TERRAFORM_AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
          TERRAFORM_AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
          CRUNCHY_TEAM_ID: ${{ vars.CRUNCHY_TEAM_ID }}
          CRUNCHY_API_KEY: ${{ secrets.CRUNCHY_API_KEY }}
          ASPIRE_AWS_ACCESS_KEY_ID: ${{ secrets.ASPIRE_AWS_ACCESS_KEY_ID }}
          ASPIRE_AWS_SECRET_ACCESS_KEY: ${{ secrets.ASPIRE_AWS_SECRET_ACCESS_KEY }}
          GIT_PAT: ${{ secrets.GIT_PAT }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          backend: ${{ matrix.backend }}
          WORKING_DIR: ./au
      - name: Deploy With Terraform Attempt 3
        id: deployAttempt3
        uses: ./.github/actions/tf-deploy-composite
        if: steps.deployAttempt1.outcome == 'failure' && steps.deployAttempt2.outcome == 'failure'
        continue-on-error: true
        with:
          TERRAFORM_AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
          TERRAFORM_AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
          CRUNCHY_TEAM_ID: ${{ vars.CRUNCHY_TEAM_ID }}
          CRUNCHY_API_KEY: ${{ secrets.CRUNCHY_API_KEY }}
          ASPIRE_AWS_ACCESS_KEY_ID: ${{ secrets.ASPIRE_AWS_ACCESS_KEY_ID }}
          ASPIRE_AWS_SECRET_ACCESS_KEY: ${{ secrets.ASPIRE_AWS_SECRET_ACCESS_KEY }}
          GIT_PAT: ${{ secrets.GIT_PAT }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          backend: ${{ matrix.backend }}
          WORKING_DIR: ./au
