name: 'Start Script via Terraform'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 7 * * *' # Everyday at 07:00 UTC (03:00 Eastern)

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: crunchy-backups
    defaults:
      run:
        working-directory: ./us-east
    strategy:
      matrix:
        backend: [aspiredu-prd-a, aspiredu-prd-b, aspiredu-prd-c, aspiredu-prd-d, aspiredu-prd-e, aspiredu-prd-g, aspiredu-prd-h, aspiredu-prd-i, aspiredu-prd-j, aspiredu-prd-k, aspiredu-prd-l, aspireprod, aspiredu-ms]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Deploy With Terraform
        uses: ./.github/actions/tf-deploy-composite
        with:
          TERRAFORM_AWS_ACCESS_KEY_ID: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
          TERRAFORM_AWS_SECRET_ACCESS_KEY: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
          CRUNCHY_TEAM_ID: ${{ vars.CRUNCHY_TEAM_ID }}
          CRUNCHY_API_KEY: ${{ secrets.CRUNCHY_API_KEY }}
          ASPIRE_AWS_ACCESS_KEY_ID: ${{ secrets.ASPIRE_AWS_ACCESS_KEY_ID }}
          ASPIRE_AWS_SECRET_ACCESS_KEY: ${{ secrets.ASPIRE_AWS_SECRET_ACCESS_KEY }}
          GIT_PAT: ${{ secrets.GIT_PAT }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          backend: ${{ matrix.backend }}

